### ISSUE TITLE
Documentation should mention export HASHKAT= is optional.

### ISSUE THREAD

**Issue by ludamad** [hashkat/hashkat#4] opened 2015-05-28 05:54 UTC
I made HASHKAT default to '.' in run.sh, if not defined. The recommendation to edit one's bashrc with a hardcoded path is a little less than ideal. It should not be necessary to manually set HASHKAT unless you have multiple configuration folders, now.

**Comment by itamblyn** [comment] 2015-05-28 18:03
Are the install instructions still relevant then?

**Comment by ludamad** [comment] 2015-05-28 18:51
They are as relevant as they were before I guess, but they could use streamlining. The change I made assumes they use a run script. I still think a run script should still be the way people run the code (common practice would be to call it 'hashkat' simply, no extension), even if it just calls hashkat_pre.py and then the binary.

**Comment by itamblyn** [comment] 2015-06-12 15:12
Ok, I don't have a problem with a script being called hashkat, and users running that rather than the binary. I understand that this is actually necessary for interactive mode to function correctly.

Basically the issue that needs to be addressed is that building and running need to be separated for normal usage (I get why it's useful for development though).

**Comment by ludamad** [comment] 2015-06-12 16:00
The run script already doesn't build if you use --force, it can be made default or called by another script

**Comment by itamblyn** [comment] 2015-06-23 00:13
I think this issue still exists.

hashkat_pre.py uses that env variable to look for DEFAULT.yaml

The idea was to get rid of the need for DEFAULT.yaml to sit in the run directory:

Currently if you run with only INFILE.yaml present and HASHKAT is not set, you get

Traceback (most recent call last):
  File "/home/i/itamblyn/itamblyn/git/hashkat/hashkat_pre.py", line 43, in <module>
    DEFAULT_FILE_NAME = os.environ['HASHKAT'] + "/DEFAULT.yaml"
  File "/usr/lib64/python2.6/UserDict.py", line 22, in __getitem__
    raise KeyError(key)
KeyError: 'HASHKAT'

**Comment by ludamad** [comment] 2015-06-23 17:10
Like I already said, if we have a runner script, it can locate itself, and thus DEFAULT.yaml

**Comment by itamblyn** [comment] 2015-06-23 17:36
Runner scripts get weird in HPC env though. Typically a user will not be
running out of the build directory

Can you try making a run script which is separate from build and I'll give
it a go on a machine with a scheduler.

Most admins aren't used to seeing build and run in the same script, so this
will avoid confusion.

**Comment by itamblyn** [comment] 2015-06-26 01:11
We need to get this run.sh thing sorted sooner rather than later. Currently the tutorials etc are based around the following procedure:

export HASHKAT=whatever
invoke hashkat_pre.py
run hashkat (the binary)

It's not too late to change the tutorials, so if we're going to a self discovering script, let's do that now so the videos / text is accurate.

**Comment by kryczko** [comment] 2015-06-26 01:13
Why don’t we use $ cmake . && make && sudo make install to cp hashkat and hashkat_pre.py to /usr/local/bin?

**Comment by itamblyn** [comment] 2015-06-26 01:31
The issue is what is the preferred method for invocation.

My understanding is that in order to use interactive mode, we need to use
the wrapper script. That's fine, but it should be separated from the build
script.

Right now the issues are:

1) Build and run are both done in the same script
2) The run script only works from the hashkat directory. You can't run from
outside.
hashkat_pre.py and the binary can. I know that the new run script could be
set up so it works outside of the directory...so let's do that.



- Isaac

**Comment by ludamad** [comment] 2015-06-26 02:03
I don't know where you got the impression interactive mode needs the runner script, but that's not the case. We could even have the binary locate itself and invoke python if we wanted, but runner scripts are cleaner.

**Comment by itamblyn** [comment] 2015-06-26 05:11
Just tried crtl+c - does not work with binary, works fine with script.

- Isaac

**Comment by ludamad** [comment] 2015-06-26 14:39
Right, the run script provides the --handle-ctrlc flag by default, however it is not strictly necessary

**Comment by itamblyn** [comment] 2015-07-03 14:49
@nbuhagiar Please fix docs and close this.

**Comment by nbuhagiar** [comment] 2015-07-03 18:16
Discussed this on installation page in documentation

**Closed by nbuhagiar** 2015-07-03 18:16 UTC
