### ISSUE TITLE
N-Bin files in source different Regions vs Other

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#66] opened 2015-10-01 19:19 UTC
N_Bin Regions 'n' of regions built must be EXACTLY SAME as those configured in INFILE.YAML

N_Bin ideologies/agent types/preference classes, if specified as 'n'. can be configured in INFILE.YAML as 0-n 

Why the difference?

**Comment by ludamad** [comment] 2015-10-01 19:23
Duplicate of #65

**Closed by ludamad** 2015-10-01 19:23 UTC
Labels: enhancement
